### PR TITLE
Add fallback to serve JS file

### PR DESCRIPTION
**Pull request by kossnocorp**
Useful to serve libraries presented in JS: jQuery, Raphael etc

### CODE REVIEW

**Comment by kossnocorp** [comment]
Any updates on this?

**Review by xaviervia — APPROVED** [review]

**Comment by kossnocorp** [comment]
That was a silly joke, and I'm so sorry! 😅

**Comment by xaviervia** [comment]
Hahahaha 😂 

I was digging through the manual to figure out how did you publish a Gem version, I think it's been 6 years since I last did.

Thanks for clarifying 😂

**Comment by kossnocorp** [comment]
Have a great evening and thank you for taking care of 8-old pull-request 🤗

**Pull request merged**
